# Generated by Django 3.1.5 on 2021-04-08 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationDestExt', models.CharField(max_length=100)),
                ('NotificationSrcExt', models.CharField(max_length=100)),
                ('NotificationDate', models.DateTimeField(default=datetime.datetime(2021, 4, 8, 10, 4, 1, 496742, tzinfo=utc))),
            ],
        ),
    ]
