# Generated by Django 3.1.5 on 2021-04-08 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('QualificationId', models.AutoField(primary_key=True, serialize=False)),
                ('QualificationDestExt', models.CharField(max_length=100)),
                ('QualificationSrcExt', models.CharField(max_length=100)),
                ('QualificationComment', models.CharField(max_length=800)),
                ('QualificationDate', models.DateTimeField(default=datetime.datetime(2021, 4, 8, 12, 43, 20, 233123, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='NotificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 12, 43, 20, 232712, tzinfo=utc)),
        ),
    ]
