# Generated by Django 3.1.5 on 2021-04-08 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210408_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='QualificationSubType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='qualification',
            name='QualificationType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='NotificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 12, 56, 26, 575602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='QualificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 12, 56, 26, 576218, tzinfo=utc)),
        ),
    ]
